# -*- coding: utf-8 -*-
"""Assemble the clean delivery folder deliverables/group_33 + zip.

Includes everything needed for:
  - pred_33.csv, tm_tests_33.ipynb, tm_final_33.ipynb, report_33.pdf (mandatory)
  - notebooks/08_Agentic_Workflow.ipynb, src/, scripts/ (extra work + reproducibility)
  - results/{figures,tables,models,predictions} (cached artefacts so the notebooks run)
  - data/raw (train/test CSVs)
Excludes: data/processed (153 MB embeddings - regenerable), logs, git, caches.
"""

import shutil
import zipfile
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
DST = BASE / "deliverables" / "group_33"

if DST.exists():
    shutil.rmtree(DST)
DST.mkdir(parents=True)

# ---- top-level mandatory files ----------------------------------------------
for f in ["pred_33.csv", "tm_tests_33.ipynb", "tm_final_33.ipynb",
          "report_33.pdf", "report_33.tex", "requirements.txt"]:
    shutil.copy2(BASE / f, DST / f)
    print(f"+ {f}")

# ---- directories --------------------------------------------------------------
def copy_dir(rel, patterns=None):
    src = BASE / rel
    dst = DST / rel
    dst.mkdir(parents=True, exist_ok=True)
    n = 0
    for p in sorted(src.iterdir()):
        if p.is_file():
            if patterns is None or any(p.match(g) for g in patterns):
                shutil.copy2(p, dst / p.name)
                n += 1
    print(f"+ {rel}/ ({n} files)")

copy_dir("data/raw")
copy_dir("src", ["*.py"])
copy_dir("scripts", ["*.py", "*.ps1"])
copy_dir("notebooks", ["08_Agentic_Workflow.ipynb"])
copy_dir("results/figures")
copy_dir("results/tables")
copy_dir("results/models")
copy_dir("results/predictions")

# ---- README -------------------------------------------------------------------
readme = """# group_33 - Financial Tweet Sentiment Classification
Text Mining 2025/2026 - NOVA IMS

## Deliverables
| File | Description |
|---|---|
| `pred_33.csv` | Test predictions (id, label) from the submitted single model |
| `tm_final_33.ipynb` | Final solution - single pipeline, single classification model (distilled FinBERT, OOF F1-macro 0.9134). Restart & Run All: ~2 min using the cached probabilities in `results/predictions/`; ~40 min to re-distil on a CUDA GPU if caches are removed. |
| `tm_tests_33.ipynb` | All experiments and their evaluation (EDA, preprocessing ablations, feature engineering, 12 model families, backbone search, ensemble, statistical tests). Fully executed outputs included. |
| `report_33.pdf` | Project report (11 pages) |
| `notebooks/08_Agentic_Workflow.ipynb` | Extra Challenge 2 - agentic workflow demo (runs offline, no API key) |

## Environment
`pip install -r requirements.txt` (Python 3.11, PyTorch with CUDA recommended).

## Notes
- `data/processed/` dense embeddings (153 MB) are not shipped; they are regenerated by the
  scripts in `scripts/` and only needed to re-run the frozen-embedding comparison cells in
  `tm_tests_33.ipynb` (which ship fully executed).
- All randomness is seeded (seed=42); every transformer result uses the identical
  10-fold StratifiedKFold protocol.
"""
(DST / "README.md").write_text(readme, encoding="utf-8")
print("+ README.md")

# ---- zip ----------------------------------------------------------------------
zip_path = BASE / "deliverables" / "group_33.zip"
if zip_path.exists():
    zip_path.unlink()
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
    for p in sorted(DST.rglob("*")):
        if p.is_file():
            zf.write(p, p.relative_to(DST.parent))

size_mb = zip_path.stat().st_size / 1e6
total_mb = sum(p.stat().st_size for p in DST.rglob("*") if p.is_file()) / 1e6
print(f"\nFolder: {total_mb:.1f} MB | Zip: {size_mb:.1f} MB -> {zip_path}")
