# -*- coding: utf-8 -*-
"""Second surgical pass on tm_tests_33.ipynb: evaluation section shows the
SUBMITTED distilled model; guards for missing data/processed caches."""

import json
from pathlib import Path

NB = Path("tm_tests_33.ipynb")
nb = json.loads(NB.read_text(encoding="utf-8"))
cells = nb["cells"]

# ---- cell 19: guard for missing embeddings ----------------------------------
src = "".join(cells[19]["source"])
guard = """# Load precomputed features
# (the dense embeddings are regenerated by scripts/ if data/processed is absent)
import numpy as np, os
if not os.path.exists('data/processed/X_finbert_train.npy'):
    print('[CACHE MISSING] data/processed/*.npy not found - run the feature scripts in scripts/')
    print('The shapes and results shown below were computed with these features.')
else:
"""
body = src.split("\n", 2)[2]  # drop original first two lines (comment + import)
indented = "\n".join("    " + l if l.strip() else l for l in body.splitlines())
cells[19]["source"] = (guard + indented).splitlines(keepends=True)

# ---- cell 41: guard for missing embeddings ----------------------------------
src41 = "".join(cells[41]["source"])
src41 = src41.replace(
    "if os.path.exists('results/figures/confusion_matrix.pdf'):",
    "if os.path.exists('results/figures/confusion_matrix.pdf') and "
    "os.path.exists('data/processed/X_sbert_train.npy'):")
cells[41]["source"] = src41.splitlines(keepends=True)

# ---- cell 40: evaluation of the SUBMITTED model ------------------------------
cells[40]["source"] = """# Full classification report - SUBMITTED model (distilled FinBERT, 10-fold OOF)
import numpy as np, json
from sklearn.metrics import classification_report, f1_score

oof = None
for p in ['results/predictions/oof_proba_finbert_distilled.npy',
          'results/predictions/oof_proba_finbert_distilled.csv']:
    if os.path.exists(p):
        oof = (np.load(p) if p.endswith('.npy')
               else pd.read_csv(p)[['p0','p1','p2']].values)
        break

if oof is not None:
    y_true = train['label'].values
    y_hat = oof.argmax(1)
    d = json.load(open('results/tables/finbert_distilled_result.json'))
    print('SUBMITTED MODEL: FinBERT student distilled from the 8-encoder ensemble')
    print(f"OOF F1-macro: {d['F1-macro']:.4f} +/- {d['F1-macro_std']:.4f}")
    print(f"Accuracy:     {d['Accuracy']:.4f}")
    print(f"Precision:    {d['Precision-macro']:.4f}")
    print(f"Recall:       {d['Recall-macro']:.4f}")
    print()
    print(classification_report(y_true, y_hat, target_names=['Bearish','Bullish','Neutral']))

# Classical-ML reference (best frozen-embedding experiment)
final_best = pd.read_csv('results/tables/full_comparison_final.csv', index_col=0).iloc[0]
print(f'Best classical experiment for reference: {final_best["Model"]} '
      f'(F1-macro {final_best["F1-macro"]:.4f})')
""".splitlines(keepends=True)

# ---- cell 46: pred verification states the source model ----------------------
cells[46]["source"] = """# Verify pred_33.csv (generated by tm_final_33.ipynb - single distilled model)
pred = pd.read_csv('pred_33.csv')
print(f'Predictions shape: {pred.shape}')
print(f'Columns: {pred.columns.tolist()}')
print(f'\\nDistribution:')
print(pred['label'].value_counts().sort_index().rename({0:'Bearish',1:'Bullish',2:'Neutral'}))
print(f'\\nFirst 5:')
print(pred.head())
assert len(pred) == 2388,                        'Wrong number of predictions!'
assert list(pred.columns) == ['id', 'label'],    'Columns must be [id, label]!'
assert set(pred['label'].unique()) == {0, 1, 2}, 'Labels must be {0,1,2}!'
assert pred['label'].isna().sum() == 0,          'NaN labels!'
assert pred['id'].is_unique,                     'Duplicate ids!'
print('\\nAll assertions PASSED.')
print('Source: single distilled FinBERT (OOF F1-macro 0.9134) - Guidelines 5.2 compliant.')
""".splitlines(keepends=True)

NB.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
print("tm_tests_33.ipynb updated (pass 2)")
